---
title: "Graphics with ggplot2"
author: "Kirill Batyuk"
date: "October 22, 2018"
output: html_document
---


```{r packages}


#install.packages("tidyverse")

library(tidyverse)

#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")

```


Start with the California ("ca") dataset

```{r}
head(ca)
View(ca)
```

Plot visitation of all CA National Parks over time

```{r}
ggplot(data=ca) +
  geom_point(aes(x = year, y= visitors))

```


```{r}
ggplot(data=ca) +
  geom_point(aes(x = year, y= visitors, color = park_name))

```


```{r}
ggplot(data=ca) +
  geom_point(aes(x = year, y= visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation")

```

```{r}
ggplot(data=ca) +
  geom_point(aes(x = year, y= visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
  theme_bw() + #this utilized the black and white theme
  theme(legend.title = element_blank()) #this removed the legend title

```
```{r}
head(se)
```


```{r}
ggplot(data=se) +
  geom_point(aes(x = year, y= visitors, color = state)) +
  labs(x = "Year",
       y = "Visitation",
       title = "South East by State") +
  theme_light() + #this utilized the black and white theme
  
  theme(legend.title = element_blank(), #this removed the legend title
        axis.text.x = element_text(angle=45, size=14))
  
```

#Faceting plots

```{r}
ggplot(data=se)+
  geom_point(aes(x=year, y=visitors, color=park_name)) +
  facet_wrap(~ state, scales = "free") +
  theme(axis.text.x = element_text(angle=90))
```


# geoms

```{r}

ggplot(data = se) +
  geom_jitter(aes(x=park_name, y=visitors), alpha = 0.4, width = 0.1) +
  coord_flip()
```

```{r}
ggplot(se) +
  geom_line(aes(x=year, y=visitors, color=park_name)) +
  theme_bw()


```


#Multiple goms on one plot

```{r}

ggplot(data = acadia) +
  geom_point(aes(x=year, y=visitors))+
  geom_line(aes(x=year, y=visitors))+
  geom_smooth(aes(x=year, y=visitors))


```

#Same as above but less typing:

```{r}

ggplot(data = acadia, aes(x=year, y=visitors)) +
  geom_point()+
  geom_line()+
  geom_smooth()


```



#bar charts


```{r}

ggplot(data = visit_16, aes(x=state, y=visitors, fill = park_name)) +
  geom_bar(stat = "identity", position ="dodge")


```

#Save a ggplot

```{r}

myplot <- ggplot(data = visit_16, aes(x=state, y=visitors, fill = park_name)) +
  geom_bar(stat = "identity", position ="dodge")

myplot
ggsave (filename = "myplot.png", myplot)

```

