---
title: "Data Wrangling"
author: "Kirill Batyuk"
date: "October 22, 2018"
output: html_document
---
```{r}

library(tidyverse) # install.packages("tidyverse")

```


```{r}

## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

#Inspect Dataset

gapminder #looks at all the data

head(gapminder) #head of dataset, first 6 rows
tail(gapminder) #last 6 rows
head(gapminder, 3) #first 3 rows

#summary statistics
str(gapminder) # data tructure
summary(gapminder)


#install.packages("skimr")
skimr::skim(gapminder)

names(gapminder) #column names
dim(gapminder) # dimentions
ncol(gapminder) #number of columns
nrow(gapminder) #number of rows

#reverse-engineer dim
c(nrow(gapminder), ncol(gapminder))


```



```{r}
#filter by rows
filter(gapminder,lifeExp < 29)
filter(gapminder, country == "Mexico") #display one country
filter(gapminder, country %in% c("Mexico", "Peru")) #display multiple countries
filter(gapminder, country == "Mexico", year == 2002)
```


```{r}
sweden <- filter(gapminder, country == "Sweden")
mean(sweden$lifeExp)
```


```{r}
#select by columns
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp) #exludes columns

#use selet and filter together
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia,-continent, -lifeExp)


```


Pipe operator will change your life

```{r}
#this
gapminder %>% head()
#same as this
head(gapminder, 3)

```


```{r}

#improve above
gap_cambodia <- gapminder %>% filter(country == "Cambodia")
gap_cambodia2 <- gap_cambodia %>% select(-continent, -lifeExp)

#same as this but better:

gap_cambodia <- gapminder %>%
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)
```


```{r}
#mutate adds new variables

gapminder %>% 
  mutate(index = 1:nrow(gapminder)) #adds rownumbers 1 - end

gapminder %>% 
  mutate(planet = "Earth") #adds earth as planent to every row

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

## Callenge
## find the maximum gdpPerCap of egypt and Vietnam. Create a new column. (one number that is max of two countries)

gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  mutate(gdp = pop * gdpPercap, max_gdp = max(gdp)) 

```

## 'group_by()' groups!

```{r}
##with mutate90
gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap,
         max_gdp = max(gdp)) %>% 
  ungroup()

```


```{r}
##with summarize() or summarise()
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup()

```


#arrange() arranges columns

```{r}
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup() %>% 
  arrange(max_gdp)
```







